insecureJs:
  namespace: insecure-js
  appName: insecure-js
  containerName: insecure-js
  service:
    name: insecure-js
    port: 3000
    targetPort: 3000
  replicas: 1
  image:
    repository: confusedcrib/insecure-js
    tag: latest
  containerPort: 3000

insecureJava:
  namespace: insecure-java
  appName: insecure-java
  containerName: insecure-java
  service:
    name: insecure-java
    port: 8080
    targetPort: 8080
  replicas: 1
  image:
    repository: confusedcrib/insecure-java
    tag: latest
  containerPort: 8080
  
busybox:
  namespace: busybox
  replicas: 1
  image: busybox:1.37.0
  command: ["sleep", "3600"]

insecureApp:
  #namespace: default
  namespace: insecure-app
  appName: insecure-app
  replicas: 1
  image:
    repository: confusedcrib/insecure-app
    tag: latest
  ports:
    http: 8080
    ssh: 22

workloadSecurityEvaluator:
  namespace: default
  appName: workload-security-evaluator
  replicas: 1
  image:
    repository: confusedcrib/workload-security-evaluator
    tag: 1
  ports:
    http: 8080
    ssh: 22
