# Define a variable for the Google Cloud project ID
projectId: gbbsec003

#to be used for this:
#repository: gcr.io/{{ .Values.projectId }}/insecure-js



insecureJs:
  namespace: insecure-js
  appName: insecure-js
  containerName: insecure-js
  service:
    name: insecure-js
    port: 3000
    targetPort: 3000
  replicas: 1
  image:
    #repository: xangui/insecure-js
    repository: gcr.io/gbbsec003/insecure-js

    tag: latest
  containerPort: 3000

insecureJava:
  namespace: insecure-java
  appName: insecure-java
  containerName: insecure-java
  service:
    name: insecure-java
    port: 8080
    targetPort: 8080
  replicas: 1
  image:
    #repository: xangui/insecure-java
    repository: gcr.io/gbbsec003/insecure-java
    tag: latest
  containerPort: 8080

#use latest version  
busybox:
  namespace: busybox
  replicas: 1
  image: busybox:1.37.0
  command: ["sleep", "3600"]

insecureApp:
  #namespace: default
  namespace: insecure-app
  appName: insecure-app
  replicas: 1
  image:
    #repository: xangui/insecure-app
    repository: gcr.io/gbbsec003/insecure-app
    tag: latest
  ports:
    http: 8080
    ssh: 22

workloadSecurityEvaluator:
  #namespace: default
  namespace: workload-security-evaluator
  appName: workload-security-evaluator
  replicas: 1
  image:
    #repository: xangui/workload-security-evaluator
    repository: gcr.io/gbbsec003/workload-security-evaluator
    tag: 1
  ports:
    http: 8080
    ssh: 22
